-- Chat identifiers become random opaque strings instead of sequential integers.
-- Existing rows keep working: their integer ids are preserved verbatim as text
-- ("1", "2", ...), so previously shared links still resolve. New chats get a
-- fresh random id generated by the server.
--
-- The three foreign keys that point at chats.id must be dropped before the
-- referenced column's type can change, then recreated afterwards.

ALTER TABLE "agent_runs" DROP CONSTRAINT IF EXISTS "agent_runs_chatId_chats_id_fk";--> statement-breakpoint
ALTER TABLE "chat_messages" DROP CONSTRAINT IF EXISTS "chat_messages_chatId_chats_id_fk";--> statement-breakpoint
ALTER TABLE "conversation_memories" DROP CONSTRAINT IF EXISTS "conversation_memories_chatId_chats_id_fk";--> statement-breakpoint
ALTER TABLE "chats" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
DROP SEQUENCE IF EXISTS "chats_id_seq";--> statement-breakpoint
ALTER TABLE "agent_runs" ALTER COLUMN "chatId" SET DATA TYPE varchar(24) USING "chatId"::varchar(24);--> statement-breakpoint
ALTER TABLE "agent_stop_requests" ALTER COLUMN "chatId" SET DATA TYPE varchar(24) USING "chatId"::varchar(24);--> statement-breakpoint
ALTER TABLE "agent_vm_runs" ALTER COLUMN "chatId" SET DATA TYPE varchar(24) USING "chatId"::varchar(24);--> statement-breakpoint
ALTER TABLE "chat_messages" ALTER COLUMN "chatId" SET DATA TYPE varchar(24) USING "chatId"::varchar(24);--> statement-breakpoint
ALTER TABLE "chats" ALTER COLUMN "id" SET DATA TYPE varchar(24) USING "id"::varchar(24);--> statement-breakpoint
ALTER TABLE "conversation_memories" ALTER COLUMN "chatId" SET DATA TYPE varchar(24) USING "chatId"::varchar(24);--> statement-breakpoint
ALTER TABLE "agent_runs" ADD CONSTRAINT "agent_runs_chatId_chats_id_fk" FOREIGN KEY ("chatId") REFERENCES "public"."chats"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_chatId_chats_id_fk" FOREIGN KEY ("chatId") REFERENCES "public"."chats"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversation_memories" ADD CONSTRAINT "conversation_memories_chatId_chats_id_fk" FOREIGN KEY ("chatId") REFERENCES "public"."chats"("id") ON DELETE cascade ON UPDATE no action;
