import express from "express";
import { createExpressMiddleware } from "@trpc/server/adapters/express";
import { parse as parseCookie } from "cookie";
import { appRouter } from "./routers";
import { createContext } from "./_core/context";
import { sdk } from "./_core/sdk";
import { COOKIE_NAME } from "@shared/const";
import { runAutomationForScheduleTask } from "./automations";
import { createHeartbeatJob, updateHeartbeatJob } from "./_core/heartbeat";
import { createUserAutomation, deleteUserAutomation, getUserAutomation, listUserAutomations, runUserAutomationForScheduleTask, setUserAutomationScheduleTask, updateUserAutomation, USER_AUTOMATION_CRONS } from "./userAutomations";
import { automationPlannerRouter } from "./automationPlannerRoute";
import { findWorkspaceOwnerByTelegramToken, getTelegramCredentialsForUser, deleteChatForUser, listChatsForUser, updateTelegramChatForUser, createChatForUser } from "./db";
import { runWorkspaceAgent, autoTitleChatForUser } from "./workspaceAgent";
import { ENV } from "./_core/env";
import { answerTelegramCallbackQuery, sendTelegramMessage } from "./telegram";
import { getTelegramModelSettingsForUser, updateTelegramModelSettingsForUser } from "./telegramModelSettings";

const MAX_TELEGRAM_CHATS = 100;
async function pruneChatsIfNeeded(ownerId: number): Promise<void> { const chats = await listChatsForUser(ownerId); if (chats.length > MAX_TELEGRAM_CHATS) { const toDelete = chats.slice(MAX_TELEGRAM_CHATS); await Promise.all(toDelete.map(c => deleteChatForUser(ownerId, c.id))); console.info(`[Telegram webhook] pruned ${toDelete.length} stale chats for owner ${ownerId}`); } }
export const app = express(); app.disable("x-powered-by");
app.use((_req, res, next) => { res.setHeader("X-Content-Type-Options", "nosniff"); res.setHeader("X-Frame-Options", "DENY"); res.setHeader("Referrer-Policy", "no-referrer"); res.setHeader("Permissions-Policy", "camera=(), microphone=(), geolocation=()"); res.setHeader("Cross-Origin-Opener-Policy", "same-origin"); res.setHeader("Cross-Origin-Resource-Policy", "same-origin"); res.setHeader("Cache-Control", "private, no-store, max-age=0"); if (process.env.NODE_ENV === "production") res.setHeader("Strict-Transport-Security", "max-age=31536000; includeSubDomains"); next(); });
app.use(express.json({ limit: "1mb" })); app.use(express.urlencoded({ limit: "1mb", extended: true })); app.use("/api/trpc", createExpressMiddleware({ router: appRouter, createContext }));
app.use(automationPlannerRouter);
function sessionToken(req: express.Request) { return parseCookie(req.headers.cookie ?? "")[COOKIE_NAME] ?? ""; }
async function authenticatedUser(req: express.Request, res: express.Response) { const user = await sdk.authenticateRequest(req); if (!user) { res.status(401).json({ error: "Unauthorized" }); return null; } return user; }

app.get("/api/user-automations", async (req, res) => { try { const user = await authenticatedUser(req, res); if (!user) return; return res.json(await listUserAutomations(user.id)); } catch (error) { console.error("User automation list failed", error); return res.status(500).json({ error: "Could not load automations." }); } });
app.post("/api/user-automations", async (req, res) => { try { const user = await authenticatedUser(req, res); if (!user) return; const { name, instructions, frequency = "daily" } = req.body ?? {}; if (typeof name !== "string" || name.trim().length < 1 || name.trim().length > 120) return res.status(400).json({ error: "Give the automation a name." }); if (typeof instructions !== "string" || instructions.trim().length < 3 || instructions.trim().length > 8000) return res.status(400).json({ error: "Describe what the automation should do." }); if (!(frequency in USER_AUTOMATION_CRONS)) return res.status(400).json({ error: "Invalid automation schedule." }); return res.status(201).json(await createUserAutomation(user.id, { name: name.trim(), instructions: instructions.trim(), frequency: frequency as any, scheduleCron: USER_AUTOMATION_CRONS[frequency as keyof typeof USER_AUTOMATION_CRONS], scheduleTimezone: "UTC", executionPrompt: instructions.trim(), args: {}, definition: {} })); } catch (error) { console.error("User automation create failed", error); return res.status(500).json({ error: "Could not create automation." }); } });
app.patch("/api/user-automations/:id", async (req, res) => { try { const user = await authenticatedUser(req, res); if (!user) return; const id = Number(req.params.id); if (!Number.isInteger(id) || id <= 0) return res.status(400).json({ error: "Invalid automation." }); const existing = await getUserAutomation(user.id, id); if (!existing) return res.status(404).json({ error: "Automation not found." }); const body = req.body ?? {}; const frequency = body.frequency === undefined ? undefined : String(body.frequency); if (frequency !== undefined && !(frequency in USER_AUTOMATION_CRONS) && frequency !== "custom") return res.status(400).json({ error: "Invalid automation schedule." }); const nextEnabled = body.enabled === undefined ? existing.enabled : Boolean(body.enabled); const nextCron = typeof body.scheduleCron === "string" ? body.scheduleCron : existing.scheduleCron; const token = sessionToken(req); if (nextEnabled && !token) return res.status(412).json({ error: "Your Nova session is not ready to create a background schedule. Refresh and try again." }); if (nextEnabled) { if (!/^0\s+\S+\s+\S+\s+\S+\s+\S+\s+\S+$/.test(nextCron)) return res.status(400).json({ error: "This automation has an invalid schedule." }); if (existing.scheduleCronTaskUid) await updateHeartbeatJob(existing.scheduleCronTaskUid, { cron: nextCron, path: "/api/scheduled/user-automation", method: "POST", enable: true }, token); else { const scheduled = await createHeartbeatJob({ name: `nova-user-automation-${existing.id}`, cron: nextCron, path: "/api/scheduled/user-automation", method: "POST", description: `User automation: ${existing.name}` }, token); await setUserAutomationScheduleTask(user.id, existing.id, scheduled.taskUid); } } else if (existing.scheduleCronTaskUid && token) { await updateHeartbeatJob(existing.scheduleCronTaskUid, { enable: false }, token); } const updated = await updateUserAutomation(user.id, id, { name: typeof body.name === "string" ? body.name.trim() : undefined, instructions: typeof body.instructions === "string" ? body.instructions.trim() : undefined, frequency: frequency as any, scheduleCron: nextCron, scheduleTimezone: typeof body.scheduleTimezone === "string" ? body.scheduleTimezone : undefined, executionPrompt: typeof body.executionPrompt === "string" ? body.executionPrompt.trim() : undefined, args: body.args && typeof body.args === "object" ? body.args : undefined, definition: body.definition && typeof body.definition === "object" ? body.definition : undefined, enabled: nextEnabled }); if (!updated) return res.status(404).json({ error: "Automation not found." }); return res.json(updated); } catch (error) { console.error("User automation update failed", error); return res.status(500).json({ error: error instanceof Error ? error.message : "Could not update automation." }); } });
app.delete("/api/user-automations/:id", async (req, res) => { try { const user = await authenticatedUser(req, res); if (!user) return; const id = Number(req.params.id); if (!Number.isInteger(id) || id <= 0) return res.status(400).json({ error: "Invalid automation." }); const existing = await getUserAutomation(user.id, id); if (!existing) return res.status(404).json({ error: "Automation not found." }); const token = sessionToken(req); if (existing.scheduleCronTaskUid && token) { try { await updateHeartbeatJob(existing.scheduleCronTaskUid, { enable: false }, token); } catch {} } await deleteUserAutomation(user.id, id); return res.json({ success: true }); } catch (error) { console.error("User automation delete endpoint error", error); return res.status(500).json({ error: "Could not delete automation." }); } });
app.post("/api/scheduled/user-automation", async (req, res) => { try { const user = await sdk.authenticateRequest(req); if (!user.isCron || !user.taskUid) return res.status(403).json({ error: "cron-only" }); const outcome = await runUserAutomationForScheduleTask(user.taskUid); return res.status(200).json({ ok: true, outcome }); } catch (error) { console.error("[User automation schedule] Callback failed", error); return res.status(500).json({ error: "user-automation-callback-failed" }); } });
app.post("/api/scheduled/automation", async (req: express.Request, res: express.Response) => { try { const user = await sdk.authenticateRequest(req); if (!user.isCron || !user.taskUid) return res.status(403).json({ error: "cron-only" }); const outcome = await runAutomationForScheduleTask(user.taskUid); if (!outcome) return res.status(200).json({ ok: true, skipped: "orphaned-schedule" }); if (outcome.failed > 0) throw new Error("The scheduled automation recorded a failed run and will be retried."); return res.status(200).json({ ok: true, outcome }); } catch (error) { console.error("[Automation schedule] Callback failed", error); return res.status(500).json({ error: "automation-callback-failed", timestamp: new Date().toISOString(), context: { path: req.path } }); } });
app.post("/api/chat/delete", async (req: express.Request, res: express.Response) => { try { const user = await authenticatedUser(req, res); if (!user) return; const chatId = Number(req.body?.chatId); if (!Number.isInteger(chatId) || chatId <= 0) return res.status(400).json({ error: "Missing or invalid chatId" }); const deleted = await deleteChatForUser(user.id, chatId); if (!deleted) return res.status(404).json({ error: "Chat not found" }); return res.status(200).json({ success: true }); } catch (error) { console.error("Chat delete endpoint error", error); return res.status(500).json({ error: "Nova could not delete this conversation." }); } });
app.post("/api/chat/stream", async (req: express.Request, res: express.Response) => { try { const user = await authenticatedUser(req, res); if (!user) return; const { chatId, content } = req.body ?? {}; if (!chatId || typeof content !== "string" || !content.trim()) { res.status(400).json({ error: "Missing chatId or content" }); return; } res.setHeader("Content-Type", "text/event-stream"); res.setHeader("Cache-Control", "no-cache"); res.setHeader("Connection", "keep-alive"); res.flushHeaders(); const writeEvent = (event: unknown) => { res.write(`data: ${JSON.stringify(event)}\n\n`); }; await runWorkspaceAgent(user.id, Number(chatId), content.trim(), { onEvent: event => writeEvent(event), onChunk: chunk => writeEvent({ choices: [{ delta: { content: chunk } }] }) }); res.write("data: [DONE]\n\n"); res.end(); void autoTitleChatForUser(user.id, Number(chatId)); } catch (error) { console.error("Chat stream endpoint error", error); if (!res.headersSent) res.status(500).json({ error: "Nova could not start this response. Please retry shortly." }); else res.end(); } });

async function handleTelegramUpdate(token: string, req: express.Request, res: express.Response): Promise<void> { try { const update = req.body; const callback = update.callback_query; if (callback?.data && callback?.message?.chat?.id !== undefined) { const callbackChatId = String(callback.message.chat.id); const ownerId = await findWorkspaceOwnerByTelegramToken(token, callbackChatId); if (!ownerId) { await answerTelegramCallbackQuery(token, String(callback.id), "This Telegram chat is not linked to Nova."); res.status(200).json({ ok: true, skipped: "unlinked-callback" }); return; } const match = String(callback.data).match(/^nova_model_(\d+)$/); if (!match) { await answerTelegramCallbackQuery(token, String(callback.id)); res.status(200).json({ ok: true, skipped: "unknown-callback" }); return; } const settings = await getTelegramModelSettingsForUser(ownerId); const options = settings.options as Array<{ id: string }>; const index = Number(match[1]); const selected = Number.isInteger(index) && index >= 0 && index < options.length ? options[index] : undefined; if (!selected) { await answerTelegramCallbackQuery(token, String(callback.id), "That model is no longer available."); res.status(200).json({ ok: true, skipped: "stale-model" }); return; } await updateTelegramModelSettingsForUser(ownerId, { provider: "nvidia-nim", modelId: selected.id }); await answerTelegramCallbackQuery(token, String(callback.id), `Selected ${selected.id}`); await sendTelegramMessage(token, callbackChatId, `✅ Model selected: ${selected.id}`); res.status(200).json({ ok: true, replied: "model-callback" }); return; }
  const message = update.message ?? update.channel_post; if (!message?.text) { res.status(200).json({ ok: true, skipped: "no-text" }); return; } const chatId = String(message.chat.id); const text = String(message.text).trim(); if (!text) { res.status(200).json({ ok: true, skipped: "empty-text" }); return; } const ownerId = await findWorkspaceOwnerByTelegramToken(token, chatId); if (!ownerId) { const isDefaultBot = Boolean(ENV.defaultTelegramBotToken && token === ENV.defaultTelegramBotToken); if (isDefaultBot) { const linkUrl = `https://nova-cloud-computer.vercel.app`; await sendTelegramMessage(token, chatId, `This Telegram chat is not yet linked to a Nova workspace. Open ${linkUrl} and use the Telegram link button (sends /start with nova_app_link) to link your account. Then send your message again.`); res.status(200).json({ ok: true, skipped: "unlinked-shared-bot" }); } else { res.status(404).json({ error: "bot-not-configured", debug: { isDefaultTok: ENV.defaultTelegramBotToken.length, tokenEq: token === ENV.defaultTelegramBotToken } }); } return; } const isAppLink = text.toLowerCase().includes("nova_app_link"); if (isAppLink) void updateTelegramChatForUser(ownerId, chatId).catch(() => {}); else { const current = await getTelegramCredentialsForUser(ownerId).catch(() => undefined); if (!current?.chatId || current.chatId === chatId) void updateTelegramChatForUser(ownerId, chatId).catch(() => {}); }
  if (text === "/models" || text === "/model") { const settings = await getTelegramModelSettingsForUser(ownerId); const options = settings.options as Array<{ id: string }>; if (!options.length) { await sendTelegramMessage(token, chatId, "No NVIDIA models are currently available. Please try again shortly."); } else { const buttons = options.map((model, index) => ({ text: `${model.id}${model.id === settings.modelId ? " ✓" : ""}`, callback_data: `nova_model_${index}` })); const rows: Array<Array<{ text: string; callback_data: string }>> = []; for (let i = 0; i < buttons.length; i += 2) rows.push(buttons.slice(i, i + 2)); await sendTelegramMessage(token, chatId, `Choose the model to use for Telegram and web chat:\n\nCurrent: ${settings.modelId || "Not selected"}`, undefined, { inlineKeyboard: rows }); } res.status(200).json({ ok: true, replied: "models" }); return; }
  const modelCommand = text.match(/^\/model\s+(.+)$/i); if (modelCommand) { const settings = await getTelegramModelSettingsForUser(ownerId); const options = settings.options as Array<{ id: string }>; const requested = modelCommand[1].trim(); const index = Number(requested); const selected = Number.isInteger(index) && index >= 1 && index <= options.length ? options[index - 1] : options.find(model => model.id === requested); if (!selected) { await sendTelegramMessage(token, chatId, "I couldn't find that model. Send /models to see the current list."); } else { await updateTelegramModelSettingsForUser(ownerId, { provider: "nvidia-nim", modelId: selected.id }); await sendTelegramMessage(token, chatId, `Model selected: ${selected.id}`); } res.status(200).json({ ok: true, replied: "model" }); return; }
  if (text === "/start" || text.toLowerCase() === "start" || text.toLowerCase().startsWith("/start ")) { const startMessage = "👋 Welcome to Nova Cloud Computer!\n\n" + "I'm your AI assistant inside this workspace. You can ask me to:\n" + "• Create, rename, move, or delete files\n" + "• Run a VM or sandbox when you ask\n" + "• Send Telegram messages on your behalf\n\n" + (isAppLink ? "✅ This chat is now linked to your Nova workspace. Just send me a message to get started." : "Just send me a message to get started."); await sendTelegramMessage(token, chatId, startMessage); res.status(200).json({ ok: true, replied: "start", linked: isAppLink }); return; } if (text === "/new") { const chat = await createChatForUser(ownerId, "Telegram Chat"); void pruneChatsIfNeeded(ownerId); await sendTelegramMessage(token, chatId, `New chat created (ID: ${chat.id}). Ask me anything!`); res.status(200).json({ ok: true }); return; } const chat = await createChatForUser(ownerId, "Telegram Chat"); void pruneChatsIfNeeded(ownerId); const result = await runWorkspaceAgent(ownerId, chat.id, text); const reply = String(result.message?.content ?? "I'm ready to help with this workspace."); await sendTelegramMessage(token, chatId, reply); await autoTitleChatForUser(ownerId, chat.id); res.status(200).json({ ok: true }); return; } catch (error) { console.error("[Telegram webhook] failed", error); res.status(500).json({ error: "webhook-failed" }); return; } }
app.post("/api/telegram/webhook/default", async (req, res) => { const token = ENV.defaultTelegramBotToken; if (!token) return res.status(404).json({ error: "bot-not-configured" }); await handleTelegramUpdate(token, req, res); });
app.post("/api/telegram/webhook/:token", async (req, res) => { const token = req.params.token; if (!token) return res.status(400).json({ error: "missing-token" }); await handleTelegramUpdate(token, req, res); });
app.get("/api/health", (_req: express.Request, res: express.Response) => res.status(200).json({ ok: true, service: "nova" }));
