import { sql } from "drizzle-orm";
import { getDb, getOrCreateWorkspace, updateWorkspaceModelSettingsForUser } from "./db";
import { listNvidiaModels } from "./nvidiaGateway";

type Provider = "nvidia-nim" | "custom";

export async function getTelegramModelSettingsForUser(ownerId: number) {
  const workspace = await getOrCreateWorkspace(ownerId);
  const db = await getDb();
  if (!db) throw new Error("The Nova database is unavailable.");
  const result = await db.execute(sql`SELECT "modelProvider", "modelId", "customModelId" FROM "telegram_bot_settings" WHERE "workspaceId" = ${workspace.id} LIMIT 1`);
  const row = (result as any).rows?.[0] ?? (result as any)[0];
  const provider = (row?.modelProvider ?? "nvidia-nim") as Provider;
  const modelId = row?.modelId ?? "";
  const customModelId = row?.customModelId ? Number(row.customModelId) : null;
  const options = provider === "nvidia-nim" ? await listNvidiaModels() : [];
  return { provider, modelId, customModelId, options };
}

export async function updateTelegramModelSettingsForUser(ownerId: number, input: { provider: Provider; modelId: string; customModelId?: number | null }) {
  const workspace = await getOrCreateWorkspace(ownerId);
  const db = await getDb();
  if (!db) throw new Error("The Nova database is unavailable.");
  let customModelId = input.customModelId ?? null;
  if (input.provider === "nvidia-nim") {
    const models = await listNvidiaModels(true);
    if (!models.some(option => option.id === input.modelId)) throw new Error("That NVIDIA model is not currently available.");
  }
  if (input.provider === "custom") {
    if (!customModelId) throw new Error("Choose a custom model.");
    const check = await db.execute(sql`SELECT id, "modelId" FROM "custom_models" WHERE id = ${customModelId} AND "workspaceId" = ${workspace.id} LIMIT 1`);
    const custom = (check as any).rows?.[0] ?? (check as any)[0];
    if (!custom) throw new Error("That custom model is not available in your workspace.");
    input = { ...input, modelId: custom.modelId };
  }
  await db.execute(sql`UPDATE "telegram_bot_settings" SET "modelProvider" = ${input.provider}, "modelId" = ${input.modelId}, "customModelId" = ${customModelId}, "updatedAt" = now() WHERE "workspaceId" = ${workspace.id}`);

  // The workspace agent is the execution path shared by web chat and Telegram.
  // Keep the selected Telegram model applied to the workspace agent so the next
  // Telegram message is actually generated by the model the user selected.
  await updateWorkspaceModelSettingsForUser(ownerId, {
    activeProvider: input.provider,
    activeModelId: input.modelId,
    activeCustomModelId: customModelId,
  });

  return getTelegramModelSettingsForUser(ownerId);
}
